name: HoLa-Brep
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=24.3.1
  - numpy=2.2.2
  - pythonocc-core==7.8.1
  - pytorch==2.4.1
  - torchvision==0.19.1
  - torchaudio==2.4.1
  - pip:
      - gradio==5.16.0
      - huggingface-hub==0.28.1
      - datasets==3.3.1
      - sentence-transformers==3.3.1
      - iopath==0.1.10
      - lmdb==1.6.2
      - wandb==0.19.3
      - point_cloud_utils==0.31.0
      - chamferdist==1.0.3
      - diffusers==0.32.1
      - vector-quantize-pytorch==1.21.2
      - hydra-core==1.3.2
      - tensorboard==2.18.0
      - ray==2.40.0
      - plyfile==1.1
      - einops==0.8.0
      - h5py==3.12.1
      - opencv-python==4.10.0.84
      - matplotlib==3.10.0
      - scikit-image==0.25.0
      - trimesh==4.5.3
      - open3d==0.19.0
      - pytorch-lightning==2.5.0.post0
      - torch_geometric==2.6.1
      - pydantic<=2.10.6
      - pyg_lib==0.4.0+pt24cu124
      - torch_scatter==2.1.2+pt24cu124
      - torch_sparse==0.6.18+pt24cu124
      - torch_cluster==1.6.3+pt24cu124
      - torch_spline_conv==1.2.2+pt24cu124
      - -f https://data.pyg.org/whl/torch-2.4.1+cu124.html
      - git+https://github.com/facebookresearch/pytorch3d.git@stable
      - git+https://github.com/otaheri/chamfer_distance
      - ./pointnet2_ops_lib/.

