CUDA_VISIBLE_DEVICES=0 python -m diffusion.train_diffusion \
    trainer.gpu=1 \
    trainer.evaluate=true \
    trainer.test_output_dir=./outputs/mvr/ \
    trainer.resume_from_checkpoint=./ckpt/Diffusion_mvr_sq30_800k.ckpt \
    trainer.num_worker=4 \
    trainer.batch_size=192 \
    dataset.name=AutoEncoder_dataset3 \
    dataset.data_root=./data/organized_data \
    dataset.cond_root=./data/organized_data \
    dataset.num_max_faces=30 \
    dataset.is_aug=0 \
    dataset.condition=[multi_img] \
    dataset.cached_condition=false \
    model.num_max_faces=30 \
    model.autoencoder=AutoEncoder_1119_light \
    model.diffusion_latent=768 \
    model.in_channels=6 \
    model.beta_schedule=squaredcos_cap_v2 \
    model.autoencoder_weights=./ckpt/AE_deepcad_1100k.ckpt \
    model.condition=[multi_img] \
    model.stored_z=false \
    model.is_aug=false \
    model.name=Diffusion_condition_mvr